package dtables.locations;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class City implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public City() {
    }




}