package dtables.locations;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class City implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private dtables.locations.Location location;

   public City()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public dtables.locations.Location getLocation()
   {
      return this.location;
   }

   public void setLocation(dtables.locations.Location location)
   {
      this.location = location;
   }

   public City(java.lang.String name, dtables.locations.Location location)
   {
      this.name = name;
      this.location = location;
   }

}