package dtables.locations;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Location implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private double latitude;
   private double longitude;

   public Location()
   {
   }

   public double getLatitude()
   {
      return this.latitude;
   }

   public void setLatitude(double latitude)
   {
      this.latitude = latitude;
   }

   public double getLongitude()
   {
      return this.longitude;
   }

   public void setLongitude(double longitude)
   {
      this.longitude = longitude;
   }

   public Location(double latitude, double longitude)
   {
      this.latitude = latitude;
      this.longitude = longitude;
   }

}