package org._default.rep;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String s;

   public Person()
   {
   }

   public java.lang.String getS()
   {
      return this.s;
   }

   public void setS(java.lang.String s)
   {
      this.s = s;
   }

   public Person(java.lang.String s)
   {
      this.s = s;
   }

}