package dtables.rep;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class D implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private int intf;

   private java.lang.String prod;

   public D()
   {
   }

   public int getIntf()
   {
      return this.intf;
   }

   public void setIntf(int intf)
   {
      this.intf = intf;
   }

   public java.lang.String getProd()
   {
      return this.prod;
   }

   public void setProd(java.lang.String prod)
   {
      this.prod = prod;
   }

   public D(int intf, java.lang.String prod)
   {
      this.intf = intf;
      this.prod = prod;
   }

}