package dtables.rep;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class D implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private int intf;

   public D()
   {
   }

   public int getIntf()
   {
      return this.intf;
   }

   public void setIntf(int intf)
   {
      this.intf = intf;
   }

   public D(int intf)
   {
      this.intf = intf;
   }

}