package dtables.rep;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SimpleObject implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public SimpleObject() {
    }




}