package dtables.customers;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.Date customerSince;
   private java.lang.Double combinedBalance;

   private java.lang.String profile;

   public Customer()
   {
   }

   public java.util.Date getCustomerSince()
   {
      return this.customerSince;
   }

   public void setCustomerSince(java.util.Date customerSince)
   {
      this.customerSince = customerSince;
   }

   public java.lang.Double getCombinedBalance()
   {
      return this.combinedBalance;
   }

   public void setCombinedBalance(java.lang.Double combinedBalance)
   {
      this.combinedBalance = combinedBalance;
   }

   public java.lang.String getProfile()
   {
      return this.profile;
   }

   public void setProfile(java.lang.String profile)
   {
      this.profile = profile;
   }

   public Customer(java.util.Date customerSince, java.lang.Double combinedBalance,
         java.lang.String profile)
   {
      this.customerSince = customerSince;
      this.combinedBalance = combinedBalance;
      this.profile = profile;
   }

}