package dtables.customers;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Offer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String product;

   private java.lang.Integer customerId;

   public Offer()
   {
   }

   public java.lang.String getProduct()
   {
      return this.product;
   }

   public void setProduct(java.lang.String product)
   {
      this.product = product;
   }

   public java.lang.Integer getCustomerId()
   {
      return this.customerId;
   }

   public void setCustomerId(java.lang.Integer customerId)
   {
      this.customerId = customerId;
   }

   public Offer(java.lang.String product, java.lang.Integer customerId)
   {
      this.product = product;
      this.customerId = customerId;
   }

}