package dtables.customers;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Offer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private dtables.customers.Customer customer;
   private java.lang.String product;

   public Offer()
   {
   }

   public dtables.customers.Customer getCustomer()
   {
      return this.customer;
   }

   public void setCustomer(dtables.customers.Customer customer)
   {
      this.customer = customer;
   }

   public java.lang.String getProduct()
   {
      return this.product;
   }

   public void setProduct(java.lang.String product)
   {
      this.product = product;
   }

   public Offer(dtables.customers.Customer customer, java.lang.String product)
   {
      this.customer = customer;
      this.product = product;
   }

}