package dtables.t;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Player implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private int score;

   public Player()
   {
   }

   public int getScore()
   {
      return this.score;
   }

   public void setScore(int score)
   {
      this.score = score;
   }

   public Player(int score)
   {
      this.score = score;
   }

}