package dtables.game;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Player implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private int score;
   private boolean winner;

   public Player()
   {
   }

   public int getScore()
   {
      return this.score;
   }

   public void setScore(int score)
   {
      this.score = score;
   }

   public boolean isWinner()
   {
      return this.winner;
   }

   public void setWinner(boolean winner)
   {
      this.winner = winner;
   }

   public Player(int score, boolean winner)
   {
      this.score = score;
      this.winner = winner;
   }

}