package dtables.flights;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Flight implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String from;
   private java.lang.String to;
   private java.util.Date departure;
   private Integer capacity;
   private java.lang.String status;

   public Flight()
   {
   }

   public java.lang.String getFrom()
   {
      return this.from;
   }

   public void setFrom(java.lang.String from)
   {
      this.from = from;
   }

   public java.lang.String getTo()
   {
      return this.to;
   }

   public void setTo(java.lang.String to)
   {
      this.to = to;
   }

   public java.util.Date getDeparture()
   {
      return this.departure;
   }

   public void setDeparture(java.util.Date departure)
   {
      this.departure = departure;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public java.lang.Integer getCapacity()
   {
      return this.capacity;
   }

   public void setCapacity(java.lang.Integer capacity)
   {
      this.capacity = capacity;
   }

   public Flight(java.lang.String from, java.lang.String to,
         java.util.Date departure, java.lang.Integer capacity,
         java.lang.String status)
   {
      this.from = from;
      this.to = to;
      this.departure = departure;
      this.capacity = capacity;
      this.status = status;
   }

}