package dtables.flights;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Passenger implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.lang.String status;
   private dtables.flights.Flight flight;

   public Passenger()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public dtables.flights.Flight getFlight()
   {
      return this.flight;
   }

   public void setFlight(dtables.flights.Flight flight)
   {
      this.flight = flight;
   }

   public Passenger(java.lang.String name, java.lang.String status,
         dtables.flights.Flight flight)
   {
      this.name = name;
      this.status = status;
      this.flight = flight;
   }

}