package dtables.vacation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Vacation implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer employeeId;
   private java.lang.Integer days;

   public Vacation()
   {
   }

   public java.lang.Integer getEmployeeId()
   {
      return this.employeeId;
   }

   public void setEmployeeId(java.lang.Integer employeeId)
   {
      this.employeeId = employeeId;
   }

   public java.lang.Integer getDays()
   {
      return this.days;
   }

   public void setDays(java.lang.Integer days)
   {
      this.days = days;
   }

   public Vacation(java.lang.Integer employeeId, java.lang.Integer days)
   {
      this.employeeId = employeeId;
      this.days = days;
   }

}