package dtables.vacation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Vacation implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Vacation() {
    }




}