package dtables.cars;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Car implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String color;

   private java.util.List<java.lang.Boolean> array;

   public Car()
   {
   }

   public java.lang.String getColor()
   {
      return this.color;
   }

   public void setColor(java.lang.String color)
   {
      this.color = color;
   }

   public java.util.List<java.lang.Boolean> getArray()
   {
      return this.array;
   }

   public void setArray(java.util.List<java.lang.Boolean> array)
   {
      this.array = array;
   }

   public Car(java.lang.String color, java.util.List<java.lang.Boolean> array)
   {
      this.color = color;
      this.array = array;
   }

}