package dtables.cars;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Car implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String color;

   public Car()
   {
   }

   public java.lang.String getColor()
   {
      return this.color;
   }

   public void setColor(java.lang.String color)
   {
      this.color = color;
   }

   public Car(java.lang.String color)
   {
      this.color = color;
   }

}