package dtables.reproducer;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DataB implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer b;

   public DataB()
   {
   }

   public java.lang.Integer getB()
   {
      return this.b;
   }

   public void setB(java.lang.Integer b)
   {
      this.b = b;
   }

   public DataB(java.lang.Integer b)
   {
      this.b = b;
   }

}