package dtables.reproducer;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DataA implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public DataA() {
    }




}