package dtables.reproducer;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DataA implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer a;

   public DataA()
   {
   }

   public java.lang.Integer getA()
   {
      return this.a;
   }

   public void setA(java.lang.Integer a)
   {
      this.a = a;
   }

   public DataA(java.lang.Integer a)
   {
      this.a = a;
   }

}