package dtables.bonus_program;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Bonus implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Bonus() {
    }




}