package dtables.bonus_program;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Employee implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer yearsOfService;

	public Employee() {
	}

	public java.lang.Integer getYearsOfService() {
		return this.yearsOfService;
	}

	public void setYearsOfService(java.lang.Integer yearsOfService) {
		this.yearsOfService = yearsOfService;
	}

	public Employee(java.lang.Integer yearsOfService) {
		this.yearsOfService = yearsOfService;
	}

}