package dtables.people;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Human implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String city;
   private java.lang.Integer age;
   private java.lang.Boolean employed;

   public Human()
   {
   }

   public java.lang.String getCity()
   {
      return this.city;
   }

   public void setCity(java.lang.String city)
   {
      this.city = city;
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public java.lang.Boolean getEmployed()
   {
      return this.employed;
   }

   public void setEmployed(java.lang.Boolean employed)
   {
      this.employed = employed;
   }

   public Human(java.lang.String city, java.lang.Integer age,
         java.lang.Boolean employed)
   {
      this.city = city;
      this.age = age;
      this.employed = employed;
   }

}