package dtables.colors;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Car implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String roofColor;
   private java.lang.String doorColor;
   private java.lang.String hoodColor;

   public Car()
   {
   }

   public java.lang.String getRoofColor()
   {
      return this.roofColor;
   }

   public void setRoofColor(java.lang.String roofColor)
   {
      this.roofColor = roofColor;
   }

   public java.lang.String getDoorColor()
   {
      return this.doorColor;
   }

   public void setDoorColor(java.lang.String doorColor)
   {
      this.doorColor = doorColor;
   }

   public java.lang.String getHoodColor()
   {
      return this.hoodColor;
   }

   public void setHoodColor(java.lang.String hoodColor)
   {
      this.hoodColor = hoodColor;
   }

   public Car(java.lang.String roofColor, java.lang.String doorColor,
         java.lang.String hoodColor)
   {
      this.roofColor = roofColor;
      this.doorColor = doorColor;
      this.hoodColor = hoodColor;
   }

}